### ISSUE TITLE
ToDo list for ERAD 2018 short course

### ISSUE THREAD

**Issue by heistermann** [openradar/erad2018#2]
We are well converging towards a solution for the upcoming ERAD 2018 short course. Here's a ToDo list which we need to address well before. 

**The deadline for anything that affects the VM is June 11 2018.** After that, the final VM image for the course will be built, and participants will be informed how to download and install.

### ToDo VM (deadline: 11/6/2018)
- [x] make sure all required Python intro session notebooks are up and running --> **Scott**
- [x] make sure all required Py-ART notebooks are up and running --> **Scott/Zach/Bobby**
- [x] make sure all required BALTRAD notebooks are up and running --> **Daniel**
- [x] make sure all required wradlib notebooks are up and running --> **Maik/Kai**

### ToDo program (deadline: 1/7/2018)
- [ ] finalise open source and open science presentation --> **Daniel**
- [x] finalise git live demo session (no slides etc., just a demo of fork&pull) --> **Maik/Kai**

### ToDo VM docs (deadline: 11/6/2018)
- [x] revise the [openradar/oss_weather_radar_vm/docs](openradar/oss_weather_radar_vm) in order to make sure that the latest changes (e.g. conda environments!) are well represented in the docs. --> **Maik**
- [x] build the docs and push to [openradar/vm_docs](https://github.com/openradar/vm-docs) --> **Maik**

### ToDo course website (deadline: 11/6/2018)
The course website (http://openradarscience.org/erad2018/) contains some links through which we can provide additional information for individual course sessions. Could be only one sentence, or could be a detailed instruction, or just a link - it depdends on you. If you are resonsible for a session, you can modify the `readme.md` files in the subdirectories based on which the webpages will be rendered.
- [x] add minimal info for [open-science slot](https://github.com/openradar/erad2018/tree/master/overview-openscience) --> **Daniel**
- [x] add minimal info for [launch vm slot](https://github.com/openradar/erad2018/tree/master/vm-launch) --> **Maik**
- [x] add minimal info for [python intro slot](https://github.com/openradar/erad2018/tree/master/intro-python) --> **Scott**
- [x] add minimal info for [git live demo](https://github.com/openradar/erad2018/tree/master/git-demo) --> **Maik**
- [x] add minimal info for [Py-ART slot](https://github.com/openradar/erad2018/tree/master/pyart) --> **Scott/Zach/Bobby**
- [x] add minimal info for [BALTRAD slot](https://github.com/openradar/erad2018/tree/master/baltrad) --> **Daniel**
- [x] add minimal info for [wradlib slot](https://github.com/openradar/erad2018/tree/master/wradlib) --> **Maik**
- [x] add minimal info for [open slot](https://github.com/openradar/erad2018/tree/master/open-slot) --> **Maik**

### ToDo Gitter (deadline: 15/6/2018)
If was suggested to use Gitter in order to communicate with the participants before the course. We could use the existing `openradar/_ERAD2018` channel, if that's fine for you. In that case, we only need to
- [x] inform participants to get a GitHub account and join the `openradar/Lobby` channel. --> **Maik**

### ToDo openradarscience.org
The short course as well as the OSS keynote would be a good opportunity to advertise our https://openradarscience.org pages. The content basically lives in `openradar/openradar-landing-page`, so if you want to update anything, please submit a PR, e.g.
- [x] update, extend and beautify https://openradarscience.org

**Comment by scollis** [comment]
Thanks @heistermann ! Will be getting to this soon

**Comment by DanielMichelson** [comment]
I will get to this after the coming week. Thanks.

**Comment by scollis** [comment]
Ditto for for our team. The week just finished was a morass of bureaucracy. We will huddle on Monday

**Comment by scollis** [comment]
Zach is still out sick.. We have started but progress is slow.. Will be done soon

**Comment by heistermann** [comment]
Had an issue when trying to build the VM with the latest changes (see https://github.com/openradar/oss_weather_radar_vm/issues/46). Can anyone reproduce?

**Comment by heistermann** [comment]
Should be fixed by https://github.com/openradar/oss_weather_radar_vm/pull/47.

**Comment by heistermann** [comment]
I've successfully built the VM with the latest changes, notebooks seems to run fine. Size is now 3.4 GB, as a result of including the Py-ART sample data.

**Comment by heistermann** [comment]
I've replaced the other 0.5.0 image [here](https://drive.google.com/drive/folders/1_xIqQ6U9Bl6mnd_r3c6jBTv8cUZMHly_). Maybe you can give it a try and run it with VirtualBox.

**Comment by scollis** [comment]
Shock, horror, I have time this week :) I assume I use https://github.com/openradar/erad2018/tree/master/intro-python
And the aim is the 10 to 10:30 session?

**Comment by heistermann** [comment]
Exactly. You can use https://github.com/openradar/erad2018/tree/master/intro-python to provide content, but you can also use it just to provide a breif synopsis and entry point and then refer to a jupyter notebook that is then included in the VM built process.

**Comment by scollis** [comment]
Perfect.. So the repo is cloned and installed as part of the vagrant build. 

So it looks like my slot will be the first time we use Python or Jupyter.

@heistermann are you using a conda env for wradlib section? 

If you are, and it would be Baltrad that is the only code that uses a system Python I will make an env for the python bits or just use wradlib's env.yml

**Comment by heistermann** [comment]
@scollis No, this repo is **not** cloned as part of the vagrant built. `openradar/erad2018` only contains the code for the course's web pages. Of course you can get/clone the material/notebooks for your Python intro slot onto the VM from anywhere and any repo.

And yes, wradlib and Py-ART are both using the `openradar` conda environment, BALTRAD is using the system's Python 2.7 environment. There shouldn't be any problem with just using the `openradar` environment for the Python intro, too.

**Comment by scollis** [comment]
Intro to python session set up via PR to OSS VM repo

**Comment by scollis** [comment]
Will update course instructions soon

**Comment by scollis** [comment]
@zssherman can you grab the latest oss_VM repo and double check that the intro notebooks run..

**Comment by zssherman** [comment]
@scollis Sounds good, I'll do that now.

**Comment by zssherman** [comment]
@scollis I did a pull request for the introductory python repository. Just a spelling error fix, but the notebook downloads when creating the VM and I get no errors, so looks good to me.

**Comment by heistermann** [comment]
Seems like we're converging...

What is the status on the following items?

- make sure all required Py-ART notebooks are up and running --> Scott/Zach/Bobby
- make sure all required BALTRAD notebooks are up and running --> Daniel

Are these ready to go?

@scollis  `add minimal info for python intro slot` is still open. Do you want to add a sentence or two there?

**Comment by DanielMichelson** [comment]
All BALTRAD notebooks are up and running!
